#!/bin/bash
#
# Tenderly Testnet Launcher
#
# Creates a Tenderly VNet (mainnet fork) and outputs all env vars needed to
# run the backend (or a preview backend) against it. The fork inherits the
# mainnet CarbonController + GradientController state, so no contracts need
# to be deployed onto it.
#
# Usage:
#   npm run tenderly:create              # create testnet, print env vars + preview curl, exit
#   npm run tenderly:create -- --run     # create testnet + start the backend locally
#
# Prerequisites:
#   - TENDERLY_ACCESS_KEY, TENDERLY_USERNAME, TENDERLY_PROJECT set
#     (in shell env or in any sourced .env)
#   - jq and curl available
#   - Local PostgreSQL + Redis running (for --run mode)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"

cd "$PROJECT_DIR"

# Load .env so TENDERLY_*, ETHEREUM_RPC_ENDPOINT etc. are available without
# the caller having to export them manually. Mirrors what the TS scripts do
# via dotenv.config().
if [ -f "$PROJECT_DIR/.env" ]; then
  set -a
  # shellcheck source=/dev/null
  source "$PROJECT_DIR/.env"
  set +a
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

RUN_BACKEND=false
for arg in "$@"; do
  case "$arg" in
    --run) RUN_BACKEND=true ;;
  esac
done

SERVER_PID=""

# ─── Cleanup (only kills the backend server, never deletes the testnet) ───────

cleanup() {
  if [ -n "$SERVER_PID" ]; then
    echo -e "\n${YELLOW}Stopping server (PID $SERVER_PID)...${NC}"
    kill "$SERVER_PID" 2>/dev/null || true
    pkill -P "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  lsof -ti:3000 | xargs kill -9 2>/dev/null || true
}

if [ "$RUN_BACKEND" = true ]; then
  trap cleanup EXIT INT TERM
fi

# ─── Validate prerequisites ──────────────────────────────────────────────────

echo -e "${CYAN}==========================================${NC}"
echo -e "${CYAN}  Tenderly Testnet Launcher               ${NC}"
echo -e "${CYAN}==========================================${NC}"
echo

if [ -z "$TENDERLY_ACCESS_KEY" ]; then
  echo -e "${RED}Error: TENDERLY_ACCESS_KEY not set${NC}"
  exit 1
fi
if [ -z "$TENDERLY_USERNAME" ]; then
  echo -e "${RED}Error: TENDERLY_USERNAME not set${NC}"
  exit 1
fi
if [ -z "$TENDERLY_PROJECT" ]; then
  echo -e "${RED}Error: TENDERLY_PROJECT not set${NC}"
  exit 1
fi

if [ "$RUN_BACKEND" = true ]; then
  lsof -ti:3000 | xargs kill -9 2>/dev/null || true
  sleep 1
fi

# ─── Create Tenderly VNet ────────────────────────────────────────────────────

echo -e "${YELLOW}Creating Tenderly virtual testnet (mainnet fork)...${NC}"

TENDERLY_TESTNET_API="https://api.tenderly.co/api/v1/account/${TENDERLY_USERNAME}/project/${TENDERLY_PROJECT}/vnets"
TIMESTAMP=$(date +"%s")

RESPONSE=$(curl -sX POST "$TENDERLY_TESTNET_API" \
  -H "Content-Type: application/json" \
  -H "X-Access-Key: ${TENDERLY_ACCESS_KEY}" \
  -d '{
    "slug": "carbon-testnet-'"${TIMESTAMP}"'",
    "display_name": "Carbon Testnet '"${TIMESTAMP}"'",
    "fork_config": {
      "network_id": 1,
      "block_number": "latest"
    },
    "virtual_network_config": {
      "chain_config": {
        "chain_id": 1
      }
    },
    "sync_state_config": {
      "enabled": false
    }
  }')

TESTNET_ID=$(echo "$RESPONSE" | jq -r '.id')
RPC_URL=$(echo "$RESPONSE" | jq -r '.rpcs[0].url')

if [ -z "$TESTNET_ID" ] || [ "$TESTNET_ID" = "null" ] || [ -z "$RPC_URL" ] || [ "$RPC_URL" = "null" ]; then
  echo -e "${RED}Failed to create Tenderly testnet${NC}"
  echo "$RESPONSE" | jq . 2>/dev/null || echo "$RESPONSE"
  exit 1
fi

echo -e "  ${GREEN}Testnet created: ${TESTNET_ID}${NC}"
echo "  RPC: $RPC_URL"

INITIAL_FORK_BLOCK=$(curl -sX POST "$RPC_URL" \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' | jq -r '.result' | xargs printf "%d\n")
echo "  Initial fork block: $INITIAL_FORK_BLOCK"
echo

# ─── Write .env.tenderly ─────────────────────────────────────────────────────

ENV_FILE="$PROJECT_DIR/.env.tenderly"

cat > "$ENV_FILE" <<EOF
# Generated by tenderly/create.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Testnet ID: ${TESTNET_ID}

ETHEREUM_RPC_ENDPOINT=${RPC_URL}
IS_FORK=1
SHOULD_HARVEST=1
SHOULD_UPDATE_ANALYTICS=1

# Tenderly metadata (not consumed by the backend, kept for reference)
TENDERLY_TESTNET_ID=${TESTNET_ID}
TENDERLY_TESTNET_RPC=${RPC_URL}
TENDERLY_INITIAL_FORK_BLOCK=${INITIAL_FORK_BLOCK}
EOF

echo -e "${GREEN}Environment written to .env.tenderly${NC}"
echo

# ─── Summary ─────────────────────────────────────────────────────────────────

echo -e "${CYAN}==========================================${NC}"
echo -e "${CYAN}  Tenderly Testnet Ready                  ${NC}"
echo -e "${CYAN}==========================================${NC}"
echo
echo -e "  Testnet ID:  ${GREEN}${TESTNET_ID}${NC}"
echo -e "  RPC URL:     ${GREEN}${RPC_URL}${NC}"
echo -e "  Fork block:  ${INITIAL_FORK_BLOCK}"
echo
echo "  Env vars (copy to .env or source .env.tenderly):"
echo
echo "    ETHEREUM_RPC_ENDPOINT=${RPC_URL}"
echo "    IS_FORK=1"
echo "    SHOULD_HARVEST=1"
echo "    SHOULD_UPDATE_ANALYTICS=1"
echo
echo -e "  To delete this testnet later:"
echo -e "    ${YELLOW}npm run tenderly:delete -- ${TESTNET_ID}${NC}"
echo

# ─── Print ready-to-paste curl for creating a preview backend ────────────────

PREVIEW_API_URL="${PREVIEW_API_URL:-http://localhost:3000}"

echo -e "${CYAN}To boot a preview backend against this Tenderly fork:${NC}"
echo
echo "  curl -X POST ${PREVIEW_API_URL}/preview/backends \\"
echo "    -H 'content-type: application/json' \\"
echo "    -d '{\"tenderlyId\":\"${TESTNET_ID}\"}'"
echo
echo -e "  (override the host with PREVIEW_API_URL=https://api... before re-running this script)"
echo

# ─── Optionally start the backend ────────────────────────────────────────────

if [ "$RUN_BACKEND" = true ]; then
  echo -e "${YELLOW}Starting backend with harvesting (IS_FORK=1)...${NC}"

  SHOULD_HARVEST=1 \
  SHOULD_UPDATE_ANALYTICS=1 \
  IS_FORK=1 \
  ETHEREUM_RPC_ENDPOINT="$RPC_URL" \
  TZ=UTC \
  npx nest start &
  SERVER_PID=$!
  echo "  Server PID: $SERVER_PID"

  echo -e "${YELLOW}  Waiting for server to be ready...${NC}"
  MAX_WAIT=120
  WAITED=0
  while [ $WAITED -lt $MAX_WAIT ]; do
    if curl -s http://localhost:3000/v1/ethereum/state > /dev/null 2>&1; then
      echo -e "  ${GREEN}Server is ready (waited ${WAITED}s)${NC}"
      break
    fi
    sleep 3
    WAITED=$((WAITED + 3))
    echo "  Waiting... (${WAITED}s)"
  done

  if [ $WAITED -ge $MAX_WAIT ]; then
    echo -e "  ${RED}Server did not start within ${MAX_WAIT}s${NC}"
    exit 1
  fi

  echo
  echo -e "${GREEN}Backend is running. Press Ctrl+C to stop (testnet stays alive).${NC}"
  echo

  wait "$SERVER_PID"
fi
